
import java.awt.Image;
import java.io.*;
import javax.swing.*;
import java.util.*;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author devaji
 */
public class F1 extends javax.swing.JFrame {
SQL obj=new SQL();
public int bhk=0;
    /**
     * Creates new form F1
     */
    public F1() {
        initComponents();
        ImageIcon x=new ImageIcon(new ImageIcon("images.jpg").getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_SMOOTH ));
        jLabel2.setIcon(x);
        jList1.setVisible(false);
        jList2.setVisible(false);
        
        obj.create();
        obj.create2();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        F2 = new javax.swing.JFrame();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        F1 = new javax.swing.JFrame();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        F3 = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList();
        r1 = new javax.swing.JRadioButton();
        r2 = new javax.swing.JRadioButton();
        r3 = new javax.swing.JRadioButton();
        r6 = new javax.swing.JRadioButton();
        r7 = new javax.swing.JRadioButton();
        r8 = new javax.swing.JRadioButton();
        r11 = new javax.swing.JRadioButton();
        r12 = new javax.swing.JRadioButton();
        r13 = new javax.swing.JRadioButton();
        r14 = new javax.swing.JRadioButton();
        jButton10 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        r9 = new javax.swing.JRadioButton();
        r10 = new javax.swing.JRadioButton();
        jPanel3 = new javax.swing.JPanel();
        r4 = new javax.swing.JRadioButton();
        r5 = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        jButton14 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        b1 = new javax.swing.JRadioButton();
        b2 = new javax.swing.JRadioButton();
        b3 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        F5 = new javax.swing.JFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList();
        jButton15 = new javax.swing.JButton();
        F4 = new javax.swing.JFrame();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        jList4 = new javax.swing.JList();
        jButton12 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();

        F2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        F2.setTitle("RealHack");
        F2.setMinimumSize(new java.awt.Dimension(600, 350));
        F2.getContentPane().setLayout(null);

        jButton5.setText("Land");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton5);
        jButton5.setBounds(30, 60, 100, 60);

        jButton6.setText("House");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton6);
        jButton6.setBounds(150, 60, 100, 60);

        jButton7.setText("Office Area");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton7);
        jButton7.setBounds(270, 60, 100, 60);

        jButton8.setText("Back");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        F2.getContentPane().add(jButton8);
        jButton8.setBounds(300, 140, 100, 60);

        jLabel1.setText("Options");
        F2.getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 20, 200, 30);

        jLabel10.setText("Options");
        F2.getContentPane().add(jLabel10);
        jLabel10.setBounds(250, 20, 130, 30);

        F1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        F1.setTitle("RealHack");
        F1.setMinimumSize(new java.awt.Dimension(600, 350));
        F1.getContentPane().setLayout(null);

        jButton1.setText("Buy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        F1.getContentPane().add(jButton1);
        jButton1.setBounds(60, 100, 100, 50);

        jButton2.setText("Sell");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        F1.getContentPane().add(jButton2);
        jButton2.setBounds(170, 100, 100, 50);

        jButton3.setText("Rent");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        F1.getContentPane().add(jButton3);
        jButton3.setBounds(280, 100, 100, 50);

        jButton4.setText("Lease");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        F1.getContentPane().add(jButton4);
        jButton4.setBounds(390, 100, 100, 50);

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 154, Short.MAX_VALUE)
        );

        F1.getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 50, 510, 160);

        F3.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        F3.setTitle("RealHack");
        F3.setMinimumSize(new java.awt.Dimension(600, 600));
        F3.setResizable(false);
        F3.getContentPane().setLayout(null);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Bangalore", "Pune", "Chennai", "Delhi" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList1ValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        F3.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(670, 80, 200, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("City");
        F3.getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 30, 120, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Area");
        F3.getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 80, 120, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel7.setText("Price Range");
        F3.getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 120, 120, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Requirement");
        F3.getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 270, 120, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Purpose");
        F3.getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 390, 120, 30);

        jList2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        F3.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(680, 130, 200, 30);

        buttonGroup1.add(r1);
        r1.setText("Below Rs 200/sq. ft.");
        F3.getContentPane().add(r1);
        r1.setBounds(160, 130, 160, 23);

        buttonGroup1.add(r2);
        r2.setText("Rs 200 - Rs 1000/ sq. ft.");
        F3.getContentPane().add(r2);
        r2.setBounds(160, 150, 160, 23);

        buttonGroup1.add(r3);
        r3.setText("Rs 1000- Rs 2000/sq. ft.");
        F3.getContentPane().add(r3);
        r3.setBounds(160, 170, 160, 23);

        buttonGroup2.add(r6);
        r6.setText("Below 900 sq. ft.");
        F3.getContentPane().add(r6);
        r6.setBounds(160, 270, 160, 23);

        buttonGroup2.add(r7);
        r7.setText("900 - 1800 sq. ft.");
        F3.getContentPane().add(r7);
        r7.setBounds(160, 290, 160, 23);

        buttonGroup2.add(r8);
        r8.setText("1800-3000 sq. ft.");
        F3.getContentPane().add(r8);
        r8.setBounds(160, 310, 160, 23);

        buttonGroup3.add(r11);
        r11.setText("Contruction");
        F3.getContentPane().add(r11);
        r11.setBounds(160, 400, 160, 23);

        buttonGroup3.add(r12);
        r12.setText("Industrial");
        F3.getContentPane().add(r12);
        r12.setBounds(160, 430, 160, 23);

        buttonGroup3.add(r13);
        r13.setText("Hospital");
        F3.getContentPane().add(r13);
        r13.setBounds(160, 460, 160, 23);

        buttonGroup3.add(r14);
        r14.setText("Other");
        F3.getContentPane().add(r14);
        r14.setBounds(160, 490, 160, 23);

        jButton10.setText("Submit");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        F3.getContentPane().add(jButton10);
        jButton10.setBounds(20, 530, 100, 30);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 126, Short.MAX_VALUE)
        );

        F3.getContentPane().add(jPanel7);
        jPanel7.setBounds(150, 390, 210, 130);

        jButton11.setText("Back");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        F3.getContentPane().add(jButton11);
        jButton11.setBounds(160, 530, 100, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Bangalore", "Pune", "Chennai", "Delhi" }));
        jComboBox1.setSelectedIndex(-1);
        jComboBox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox1ItemStateChanged(evt);
            }
        });
        F3.getContentPane().add(jComboBox1);
        jComboBox1.setBounds(150, 30, 130, 30);

        F3.getContentPane().add(jComboBox2);
        jComboBox2.setBounds(150, 80, 130, 30);

        buttonGroup2.add(r9);
        r9.setText("3000-5000 sq. ft.");
        F3.getContentPane().add(r9);
        r9.setBounds(160, 330, 160, 23);

        buttonGroup2.add(r10);
        r10.setText("Above 5000 sq. ft.");
        F3.getContentPane().add(r10);
        r10.setBounds(160, 350, 160, 23);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        F3.getContentPane().add(jPanel3);
        jPanel3.setBounds(150, 260, 210, 120);

        buttonGroup1.add(r4);
        r4.setText("Rs 2000- Rs 3000/sq. ft.");
        F3.getContentPane().add(r4);
        r4.setBounds(160, 190, 160, 23);

        buttonGroup1.add(r5);
        r5.setText("Above Rs 3000/sq. ft.");
        F3.getContentPane().add(r5);
        r5.setBounds(160, 210, 160, 23);

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 206, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 116, Short.MAX_VALUE)
        );

        F3.getContentPane().add(jPanel4);
        jPanel4.setBounds(150, 120, 210, 120);

        jButton14.setText("Generate test cases");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        F3.getContentPane().add(jButton14);
        jButton14.setBounds(340, 50, 140, 50);

        jLabel21.setText("This can take a few minutes < 5 mins");
        F3.getContentPane().add(jLabel21);
        jLabel21.setBounds(310, 20, 210, 20);

        buttonGroup4.add(b1);
        b1.setText("1");
        F3.getContentPane().add(b1);
        b1.setBounds(390, 150, 50, 23);

        buttonGroup4.add(b2);
        b2.setText("2");
        F3.getContentPane().add(b2);
        b2.setBounds(390, 180, 50, 23);

        buttonGroup4.add(b3);
        b3.setText("3");
        F3.getContentPane().add(b3);
        b3.setBounds(390, 210, 50, 23);

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("BHK");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 89, Short.MAX_VALUE))
        );

        F3.getContentPane().add(jPanel5);
        jPanel5.setBounds(370, 120, 130, 120);

        F5.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        F5.setMinimumSize(new java.awt.Dimension(600, 600));
        F5.getContentPane().setLayout(null);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        F5.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(190, 70, 212, 267);

        jLabel17.setText("Search Results");
        F5.getContentPane().add(jLabel17);
        jLabel17.setBounds(10, 10, 120, 40);

        jLabel18.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F5.getContentPane().add(jLabel18);
        jLabel18.setBounds(200, 10, 290, 50);

        jLabel19.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F5.getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 350, 370, 50);

        jLabel20.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        F5.getContentPane().add(jLabel20);
        jLabel20.setBounds(20, 420, 370, 50);

        jList3.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList3ValueChanged(evt);
            }
        });
        jScrollPane5.setViewportView(jList3);

        F5.getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(10, 70, 170, 270);

        jButton15.setText("Back");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        F5.getContentPane().add(jButton15);
        jButton15.setBounds(249, 490, 110, 30);

        F4.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        F4.setMinimumSize(new java.awt.Dimension(600, 600));
        F4.getContentPane().setLayout(null);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        F4.getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(160, 20, 166, 270);

        jList4.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                jList4ValueChanged(evt);
            }
        });
        jScrollPane6.setViewportView(jList4);

        F4.getContentPane().add(jScrollPane6);
        jScrollPane6.setBounds(10, 20, 130, 270);

        jButton12.setText("Archive");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        F4.getContentPane().add(jButton12);
        jButton12.setBounds(20, 310, 120, 40);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(600, 430));
        getContentPane().setLayout(null);

        jLabel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 40, 490, 170);

        jButton9.setText("Submit");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(440, 240, 80, 23);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(80, 240, 140, 30);
        getContentPane().add(jTextField2);
        jTextField2.setBounds(290, 240, 140, 30);

        jLabel3.setText("Email");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 240, 40, 30);

        jLabel4.setText("Ph. no.");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 240, 50, 30);

        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 524, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 20, 530, 260);

        jLabel22.setForeground(new java.awt.Color(255, 0, 51));
        jLabel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel22);
        jLabel22.setBounds(20, 290, 530, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        F2.setVisible(true);
        F1.setVisible(false);
        jLabel1.setText("Buy");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        F1.setVisible(true);
        F2.setVisible(false);
        jButton5.setVisible(true);
        jButton6.setVisible(true);
        jButton7.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jButton1.doClick();
        jLabel1.setText("Sell");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jButton1.doClick();
        jLabel1.setText("Rent");
        jButton5.setVisible(false);
        jButton6.setVisible(true);
        jButton7.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jButton1.doClick();
        jLabel1.setText("Lease");
        jButton5.setVisible(false);
        jButton6.setVisible(false);
        jButton7.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        String a=jTextField1.getText(),b=jTextField2.getText();
        if(a.equals("realhack")&&b.equals("admin"))
        {
            jList4.setListData(obj.query("select * from history;","phno"));
            F4.setVisible(true);this.setVisible(false);
        }
        else if(a.contains("@")&&a.contains(".")&&b.length()==10)
        {this.setVisible(false);
        F1.setVisible(true);}
        else
        {jLabel22.setText("*Please enter correct email and phone number");}
        
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        F2.setVisible(false);
        F3.setVisible(true);
        bhk=0;
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        jPanel5.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setText("Land");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jList1ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList1ValueChanged
        // TODO add your handling code here:
        Object[] o=new Object[3];
        int in=jList1.getSelectedIndex();
        if(in==0)
        {o[0]="Koramangala";
         o[1]="HAL";
         o[2]="Infantry Road";
        }
        else if(in==1)
        {o[0]="Pune Central";
         o[1]="Airport";
         o[2]="Golf Course";}
        else if(in==2)
        {o[0]="Tambaram";
         o[1]="Vandalur";
         o[2]="Egmore";}
        else if(in==3)
        {o[0]="Sector 91";
         o[1]="Chandni Chowk";
         o[2]="Lajpat Nagar";}
        jList2.setListData(o);
    }//GEN-LAST:event_jList1ValueChanged

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        F2.setVisible(true);
        F3.setVisible(false);
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jComboBox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox1ItemStateChanged
        // TODO add your handling code here:
        Object[] o=new Object[3];
        int in=jComboBox1.getSelectedIndex();
        if(in==0)
        {o[0]="Koramangala";
         o[1]="HAL";
         o[2]="Infantry Road";
        }
        else if(in==1)
        {o[0]="Pune Central";
         o[1]="Airport";
         o[2]="Golf Course";}
        else if(in==2)
        {o[0]="Tambaram";
         o[1]="Vandalur";
         o[2]="Egmore";}
        else if(in==3)
        {o[0]="Sector 91";
         o[1]="Chandni Chowk";
         o[2]="Lajpat Nagar";}
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(o));
    }//GEN-LAST:event_jComboBox1ItemStateChanged

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        File f=new File("data.xml");
        String email=jTextField1.getText(),ph=jTextField2.getText(),minp="",maxp="",mreq="",mxreq="",purpose="",
                city=""+jComboBox1.getSelectedItem(),dist=""+jComboBox2.getSelectedItem(),bhk2="";
        if(r1.isSelected())
        {minp="0";maxp="200";}
        if(r2.isSelected())
        {minp="200";maxp="1000";}
        if(r3.isSelected())
        {minp="1000";maxp="2000";}
        if(r4.isSelected())
        {minp="2000";maxp="3000";}
        if(r5.isSelected())
        {minp="3000";maxp="999999";}
        if(r6.isSelected())
        {mreq="0";mxreq="900";}
        if(r7.isSelected())
        {mreq="900";mxreq="1800";}
        if(r8.isSelected())
        {mreq="1800";mxreq="3000";}
        if(r9.isSelected())
        {mreq="3000";mxreq="5000";}
        if(r10.isSelected())
        {mreq="5000";mxreq="999999";}
        if(r11.isSelected())
        {purpose="Construction";}
        if(r12.isSelected())
        {purpose="Industrial";}
        if(r13.isSelected())
        {purpose="Hospital";}
        if(r14.isSelected())
        {purpose="Other";}
        if(b1.isSelected())
        {bhk2="1";}
        if(b2.isSelected())
        {bhk2="2";}
        if(b3.isSelected())
        {bhk2="3";}
        try{BufferedWriter fw=new BufferedWriter(new FileWriter(f));
        fw.write("<email>"+email+"</email>");
        fw.append("<ph>"+ph+"</ph>");
        fw.append("<operation>"+jLabel1.getText()+"</operation>");
        fw.append("<suboperation>"+jLabel10.getText()+"</suboperation>");
        fw.append("<city>"+city+"</city>");
        fw.append("<area>"+dist+"</area>");
        fw.append("<minprice>"+minp+"</minprice>");
        fw.append("<maxprice>"+maxp+"</maxprice>");
        fw.append("<minreq>"+mreq+"</minreq>");
        fw.append("<maxreq>"+mxreq+"</maxreq>");
        fw.append("<purpose>"+purpose+"</purpose>");
        fw.close();
        }
        catch(Exception e){System.out.println(e);}
        int xy=(int)(System.currentTimeMillis()%10000);
        jLabel18.setText(new Date()+":"+xy);        
        jList3.setListData(obj.query("select * from record where (city=\""+city+"\" and dist=\""+dist
                        +"\" and (price between "+minp+" and "+maxp+") and (area between "+mreq+" and "+mxreq+
                ")) order by name limit 300  ;","name"));
        jLabel19.setText(new Date()+":"+(System.currentTimeMillis()%10000));
        jLabel20.setText(""+((System.currentTimeMillis()%10000)-xy)+" ms for searching "+
                obj.query("select count(*) from record ;","count(*)")[0]+" records");
        F5.setVisible(true);
        F3.setVisible(false);
        String dev[]=new String[11];
        dev[0]=email;
        dev[1]=ph;
        dev[2]=city;
        dev[3]=dist;
        dev[4]=minp;
        dev[5]=maxp;
        dev[6]=mreq;
        dev[7]=mxreq;
        dev[8]=jLabel1.getText();
        dev[9]=jLabel10.getText();
        if(bhk==0)
        dev[10]=""+bhk;
        else
            dev[10]=bhk2;
        obj.insertUser(dev);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        F3.setVisible(true);
        bhk=1;
        b1.setVisible(true);
        b2.setVisible(true);
        b3.setVisible(true);
        jPanel5.setVisible(true);
        jLabel11.setVisible(true);
        F2.setVisible(false);
        jLabel10.setText("House");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        F3.setVisible(true);
        F2.setVisible(false);
        b1.setVisible(false);
        b2.setVisible(false);
        b3.setVisible(false);
        jPanel5.setVisible(false);
        jLabel11.setVisible(false);
        jLabel10.setText("Office");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jList3ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList3ValueChanged
        // TODO add your handling code here:
        String a[]=obj.queryR("select * from record where name=\""+jList3.getSelectedValue()+"\"");
        jTextArea1.setText(a[0]+"\nCity :"+a[1]+"\nDist :"+a[2]+"\nRs"+a[3]+"/sq. ft.\n"+a[4]+"sq. ft.");
    }//GEN-LAST:event_jList3ValueChanged

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
         String a[]=new String[5];
        for(int k=0;k<4;k++)
        {String gg=""+jComboBox1.getItemAt(k);
        jComboBox1.setSelectedIndex(k);
         for(int j=0;j<3;j++)
        {String hh=""+jComboBox2.getItemAt(j);
         for(int i=0;i<100;i++)
        {Random r=new Random();
        int kl=r.nextInt(50000);
        a[0]="plot "+kl;
        a[1]=gg;
        a[2]=hh;
        a[3]=""+r.nextInt(5000);
        a[4]=""+r.nextInt(5000);
        obj.insert(a);
        }
        }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        F2.setVisible(true);
        F5.setVisible(false);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jList4ValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_jList4ValueChanged
        // TODO add your handling code here:
        String dev[]=new String[9];
        dev=obj.queryRH("select * from history where phno=\""+jList4.getSelectedValue()+"\" ;");
        jTextArea2.setText(dev[0]+"\n"+dev[1]+"\nInterested in:\n"+dev[2]+"\n"+dev[3]+"\n"+dev[6]+"->"+dev[7]+"\nBudget\nRs."+dev[4]
        +"/sq. ft.\nRs."+dev[5]+"/sq. ft.\nPreferences\n"+dev[8]+"sq. ft.\n"+dev[9]+"sq. ft.\n" );
        if(!(dev[10].equals("0")))
        {jTextArea2.append(dev[10]+" BHK");}
    }//GEN-LAST:event_jList4ValueChanged

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFrame F1;
    private javax.swing.JFrame F2;
    private javax.swing.JFrame F3;
    private javax.swing.JFrame F4;
    private javax.swing.JFrame F5;
    private javax.swing.JRadioButton b1;
    private javax.swing.JRadioButton b2;
    private javax.swing.JRadioButton b3;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList jList1;
    private javax.swing.JList jList2;
    private javax.swing.JList jList3;
    private javax.swing.JList jList4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JRadioButton r1;
    private javax.swing.JRadioButton r10;
    private javax.swing.JRadioButton r11;
    private javax.swing.JRadioButton r12;
    private javax.swing.JRadioButton r13;
    private javax.swing.JRadioButton r14;
    private javax.swing.JRadioButton r2;
    private javax.swing.JRadioButton r3;
    private javax.swing.JRadioButton r4;
    private javax.swing.JRadioButton r5;
    private javax.swing.JRadioButton r6;
    private javax.swing.JRadioButton r7;
    private javax.swing.JRadioButton r8;
    private javax.swing.JRadioButton r9;
    // End of variables declaration//GEN-END:variables
}
